services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOPATH=/go
    ports:
      - "8080:8080"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.121.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yml:/etc/otel-collector.yaml
    ports:
      - 4317:4317
      
  prometheus:
    image: prom/prometheus:v3.2.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - 16686:16686